---
title: "Pre-process the data for PENCIL input"
author: "Tiangen Chang tiangen.chang@nih.gov"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
# clear all objects including hidden objects
rm(list = ls(all.names = TRUE)) 
# free up memory and report the memory usage
gc()
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = FALSE, 
                      warning = FALSE, 
                      message = FALSE)
require(ggplot2)
ggplot2::theme_set(new = theme_bw(base_size = 12)) # sets the theme and axis font size
```

# Connect to server
```{bash}
ssh changt7@biowulf.nih.gov
sinteractive --mem=64g --cpus-per-task=32 --time=24:00:00
sinteractive --mem=128g --cpus-per-task=32 --gres=gpu:k80:2 --time=24:00:00
# --gres=lscratch:1024
module load R/
R

```

# load required package
```{r, include=FALSE}
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("UCell")
library(UCell)

#devtools::install_github("mojaveazure/seurat-disk")
#devtools::install_github('satijalab/seurat-data')
library(SeuratData)
library(SeuratDisk)

library(caret)
library(Seurat)
library(GEOquery)
library(dplyr)
library(ggplot2)
library(SingleR)
library(sctransform)
library(celldex)
library(dittoSeq)
library(SeuratWrappers)
library(harmony)
library(scuttle)
library(scran)
library(scFeatureFilter)
library(cowplot)
library(patchwork)
library(edgeR)
library(RColorBrewer)
library(stringr)

```

# set input and output directories & parameters
```{r}

dataset = 'GSE123813'

# local
data_dir <- paste0("/Users/changt7/Documents/00.PostDocWork/CancerResearch/01.Projects/00.Collaborating_projects/05.PENCIL/02.Input/", dataset, '/')
processed_dir <- paste0("../03.Results/", dataset, '/')
fig_dir <- paste0("../03.Results/", dataset, '/Figures/')

# server
shared_data_dir = paste0("/data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/02.Input/")
data_dir <- paste0(shared_data_dir, dataset, '/')
processed_dir <- paste0("/data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/", dataset, '/')
fig_dir = paste0("/data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/", dataset, "/Figures/")
```

# build seurat object from raw data
```{r}

# Read the .h5 file for SCC samples
counts <- Read10X_h5(filename = paste0(data_dir, "SCC_GSE123813_aPD1_expression.h5"))

# Create a Seurat object
seurat_obj <- CreateSeuratObject(counts = counts)
seurat_obj@assays[['RNA']]@data = seurat_obj@assays[['RNA']]@counts

cell_names_split <- strsplit(colnames(seurat_obj), "_")
# Extract 'patient', 'sample', and 'meta' strings
meta <- sapply(cell_names_split, function(x) x[1])
clinical_split <- strsplit(meta, "\\.")
tumor_type = sapply(clinical_split, function(x) x[1])
patient <- sapply(clinical_split, function(x) x[2])
timePt <- sapply(clinical_split, function(x) x[3])

seurat_obj$meta <- meta
seurat_obj$patient <- patient
seurat_obj$patient[seurat_obj$patient=='su010'] = 'su010-S'
seurat_obj$timePt <- timePt
seurat_obj$tumor_type <- tumor_type




# Read the .h5 file for BCC samples
counts <- Read10X_h5(filename = paste0(data_dir, "BCC_GSE123813_aPD1_expression.h5"))

# Create a Seurat object
seurat_obj2 <- CreateSeuratObject(counts = counts)
seurat_obj2@assays[['RNA']]@data = seurat_obj2@assays[['RNA']]@counts

cell_names_split <- strsplit(colnames(seurat_obj2), "_")
# Extract 'patient', 'sample', and 'meta' strings
meta <- sapply(cell_names_split, function(x) x[1])
clinical_split <- strsplit(meta, "\\.")
tumor_type = sapply(clinical_split, function(x) x[1])
patient <- sapply(clinical_split, function(x) x[2])
timePt <- sapply(clinical_split, function(x) x[3])

seurat_obj2$meta <- meta
seurat_obj2$patient <- patient
seurat_obj2$timePt <- timePt
seurat_obj2$tumor_type <- tumor_type


# merge SCC and BCC seurat objects into one
merged_seu <- merge(seurat_obj, seurat_obj2)


# Create a new Seurat object with the un-normalized (counts per 10000) as counts
merged_seu[["RNA"]]@data <- exp(as.matrix(merged_seu[["RNA"]]@data))-1 
merged_seu_new <- CreateSeuratObject(counts = merged_seu[["RNA"]]@data) # 
##### Add meta info. to seurat object
merged_seu_new <- AddMetaData(merged_seu_new, merged_seu@meta.data)
merged_seu_new <- NormalizeData(merged_seu_new)
merged_seu = merged_seu_new

rm(merged_seu_new)
gc()

```


# Add phenotype info 
```{r}

# Read in phenotype info.
phenotype_df = read.csv(file = paste0(data_dir,"clinicInfo.csv"))
phenotype_df = phenotype_df[,c(1,6)]
colnames(phenotype_df) = c('patient', 'ICBresponse')

##### Add phenotype info to seurat object
meta <- merged_seu@meta.data
meta$cell_names <- rownames(meta) # save row names before merge with phenotype data
meta.new <- merge(meta, phenotype_df, by.x = "patient", by.y = "patient")
rownames(meta.new) <- meta.new$cell_names # retrieve rownames 
merged_seu <- AddMetaData(merged_seu, meta.new)
merged_seu$ICBresponse[merged_seu$ICBresponse=='Yes']=1
merged_seu$ICBresponse[merged_seu$ICBresponse=='No']=0


##### add original cell annotation information
scc_cell_anno_df = read.csv(file = paste0(data_dir,"GSE123813_scc_metadata.txt"), sep='\t')
scc_cell_anno_df = scc_cell_anno_df[,c(1,4)]
bcc_cell_anno_df = read.csv(file = paste0(data_dir,"GSE123813_bcc_all_metadata.txt"), sep='\t')
bcc_cell_anno_df = bcc_cell_anno_df[,c(1,5)]
cell_anno_df = rbind(bcc_cell_anno_df, scc_cell_anno_df)
colnames(cell_anno_df) = c("cell_names", "cell_type")

meta <- merged_seu@meta.data
meta$cell_names <- rownames(meta) # save row names before merge with phenotype data
meta.new <- merge(meta, cell_anno_df, by.x = "cell_names", by.y = "cell_names")
rownames(meta.new) <- meta.new$cell_names # retrieve rownames 
merged_seu <- AddMetaData(merged_seu, meta.new)
merged_seu$cell_names=NULL


saveRDS(object = merged_seu, file = paste0(data_dir, "seu_",sampleType_name,"_all_raw.rds")) 


```

# extract CD8T cells
```{r}

merged_seu$CD8T_cell <- ifelse(grepl("CD8", merged_seu$cell_type, ignore.case = TRUE), "CD8+ T-cells", "Other")

seurat_obj_CD8T <- subset(merged_seu, subset = CD8T_cell == "CD8+ T-cells")

saveRDS(seurat_obj_CD8T, file = paste0(processed_dir,"seu_Tissue_CD8T.rds"))

```

# QC, normalization, dimension reduction, and clustering
```{r}

merged_seu = seurat_obj_CD8T

#merged_seu = readRDS(file = paste0(data_dir, "seu_",sampleType_name,"_all_raw.rds")) 


# Normalize the data
# merged_seu <- NormalizeData(merged_seu) # log(x/sum(x)*10000+1)

# Find highly variable genes
merged_seu <- FindVariableFeatures(merged_seu)

# Scale the data
merged_seu <- ScaleData(merged_seu) # pbmc <- SCTransform(pbmc, vars.to.regress = "CC.Difference")

# Perform PCA
merged_seu <- RunPCA(merged_seu, pc.genes = merged_seu@var.genes)

# Perform UMAP
merged_seu <- RunUMAP(merged_seu, reduction = "pca", dims = 1:30)

# Find neighbors
merged_seu <- FindNeighbors(merged_seu, reduction = "pca", dims = 1:30)

# Find clusters
merged_seu <- FindClusters(merged_seu, resolution = 1) # PBMC: 1   Tissue: 2

# Save to file
saveRDS(object = merged_seu, file = paste0(processed_dir, "seu_",sampleType_name,"_CD8T.rds")) 

```

# check UMAP for batch effect
```{r}
# Plot highlighted seurat clusters
#merged_seu$highlighted.samples <- ifelse(merged_seu$sample %in% c("OP5","OP8"), as.character(merged_seu$sample), "Other") # "OP9CD45N", "OP9CD45P", 

DimPlot(merged_seu, group.by = 'patient', label = TRUE, repel = TRUE, raster=FALSE)+#NoLegend()+
  #scale_color_manual(values = c("blue", "red", "green", "purple", "yellow", "orange", "gray"))+
  ggtitle("")
ggsave(filename = paste0(fig_dir, "UMAP_",sampleType_name,"_CD8T_patient.png"), height = 120, width = 140, dpi = 300, units = "mm")

```
