---
title: "Pre-process the data for PENCIL input"
author: "Tiangen Chang tiangen.chang@nih.gov"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r}
# clear all objects including hidden objects
rm(list = ls(all.names = TRUE)) 
# free up memory and report the memory usage
gc()
```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = FALSE, 
                      warning = FALSE, 
                      message = FALSE)
require(ggplot2)
ggplot2::theme_set(new = theme_bw(base_size = 12)) # sets the theme and axis font size
```

# Connect to server
```{bash}
ssh changt7@biowulf.nih.gov
sinteractive --mem=64g --cpus-per-task=32 --time=24:00:00
sinteractive --mem=128g --cpus-per-task=32 --gres=gpu:k80:2 --time=24:00:00
# --gres=lscratch:1024
module load R/
R

```

# load required package
```{r, include=FALSE}
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("UCell")
library(UCell)

#devtools::install_github("mojaveazure/seurat-disk")
#devtools::install_github('satijalab/seurat-data')
library(SeuratData)
library(SeuratDisk)

library(caret)
library(Seurat)
library(GEOquery)
library(dplyr)
library(ggplot2)
library(SingleR)
library(sctransform)
library(celldex)
library(dittoSeq)
library(SeuratWrappers)
library(harmony)
library(scuttle)
library(scran)
library(scFeatureFilter)
library(cowplot)
library(patchwork)
library(edgeR)
library(RColorBrewer)
library(stringr)

```

# set input and output directories & parameters
```{r}

dataset = 'GSE164690'

# local
data_dir <- paste0("/Users/changt7/Documents/00.PostDocWork/CancerResearch/01.Projects/00.Collaborating_projects/05.PENCIL/02.Input/", dataset, '/')
processed_dir <- paste0("../03.Results/", dataset, '/')
fig_dir <- paste0("../03.Results/", dataset, '/Figures/')

# server
shared_data_dir = paste0("/data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/02.Input/")
data_dir <- paste0(shared_data_dir, dataset, '/')
processed_dir <- paste0("/data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/", dataset, '/')
fig_dir = paste0("/data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/", dataset, "/Figures/")

```


# PBMC/Tissue cell annotation using celltypist
```{r}
sampleType_name = "Tissue" # PBMC   Tissue
merged_seu = readRDS(file = paste0(processed_dir,"seu_",sampleType_name,".rds"))

# Normalize the data
merged_seu <- NormalizeData(merged_seu) # log(x/sum(x)*10000+1)

# Find highly variable genes
merged_seu <- FindVariableFeatures(merged_seu)

# Scale the data
merged_seu <- ScaleData(merged_seu) # pbmc <- SCTransform(pbmc, vars.to.regress = "CC.Difference")

# Perform PCA
merged_seu <- RunPCA(merged_seu, pc.genes = merged_seu@var.genes)

# Perform UMAP
merged_seu <- RunUMAP(merged_seu, reduction = "pca", dims = 1:30)

# Find neighbors
merged_seu <- FindNeighbors(merged_seu, reduction = "pca", dims = 1:30)

# Find clusters
merged_seu <- FindClusters(merged_seu, resolution = 1)


# save to h5ad for celltypist
SaveH5Seurat(merged_seu, filename = paste0(processed_dir, "seu_",sampleType_name,".h5Seurat"), overwrite = TRUE)
Convert(paste0(processed_dir, "seu_",sampleType_name,".h5Seurat"), dest = "h5ad", overwrite = TRUE) # , use_hvgs = FALSE

```

# run celltypist
```{bash}

celltypist --indata /data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/GSE164690/seu_PBMC.h5ad --model Immune_All_Low.pkl --outdir /data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/GSE164690/ --prefix PBMC_celltypist_ImmuneAllLow_ --majority-voting


celltypist --indata /data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/GSE164690/seu_Tissue.h5ad --model Immune_All_Low.pkl --outdir /data/Lab_ruppin/tiangen/CancerProject/02.PENCIL/03.Results/GSE164690/ --prefix Tissue_celltypist_ImmuneAllLow_ --majority-voting


```

# add celltypist annotation to original seurat object
```{r}

prediction_labels <- read.csv(paste0(processed_dir,sampleType_name,"_celltypist_ImmuneAllLow_predicted_labels.csv"), row.names = 1)
merged_seu$cell_type_celltypist <- prediction_labels['majority_voting']

meta <- merged_seu@meta.data
meta$cell_names <- rownames(meta) # save row names before merge with phenotype data
print(colnames(meta))
keep_columns <- c("orig.ident", "nCount_RNA", "nFeature_RNA", "percent.mt", "meta", "patient", "sample","cell_type_celltypist", "cell_names")
meta = meta[keep_columns]
for (col in colnames(merged_seu@meta.data)){
  merged_seu@meta.data[col]= NULL
}
merged_seu <- AddMetaData(merged_seu, meta)
merged_seu$cell_names= NULL

saveRDS(merged_seu, file = paste0(processed_dir,"seu_",sampleType_name,".rds"))

```







# merge seurat objects of tumor and blood, save only the new samples that not covered by GSE139324
```{r}

seu_Tissue = readRDS(file=paste0(processed_dir, "seu_Tissue.rds"))
seu_Tissue_new <- subset(seu_Tissue, subset = patient %in% c("HN16", "HN17", "HN18"))


seu_PBMC = readRDS(file=paste0(processed_dir, "seu_PBMC.rds"))
seu_PBMC_new <- subset(seu_PBMC, subset = patient %in% c("HN16", "HN17", "HN18"))

merged_seu = merge(seu_Tissue_new,seu_PBMC_new)

```




# extract CD8T cells
```{r}

merged_seu$CD8T_cell <- ifelse(grepl("cytotoxic T|MAIT", merged_seu$cell_type_celltypist, ignore.case = TRUE), "CD8+ T-cells", "Other")

merged_seu_subset <- subset(merged_seu, subset = CD8T_cell == "CD8+ T-cells")

saveRDS(merged_seu, file = paste0(processed_dir,"seu_all3samples.rds"))

saveRDS(merged_seu_subset, file = paste0(processed_dir,"seu_all_CD8T.rds"))

```


